# Android SDK ve Gradle içeren bir baz görüntü seçin
FROM openjdk:8

# Gerekli araçları yükleyin
RUN apt-get update && apt-get install -y unzip wget

# Android SDK kurulum
RUN wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O sdk-tools.zip
RUN mkdir /android-sdk && unzip sdk-tools.zip -d /android-sdk && rm sdk-tools.zip

# Android ortam değişkenlerini ayarlayın
ENV ANDROID_HOME /android-sdk
ENV PATH ${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools

# Gerekli SDK bileşenlerini yükleyin
RUN yes | sdkmanager --licenses && \
    sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"

WORKDIR /app
